baseURL = 'http://localhost:1313/'
languageCode = 'vi'
title = 'Blog Lập Trình của Trần Quốc Anh'
theme = 'LoveIt'

[params]
homepage.layout = "posts"

[menu]
  [[menu.main]]
    name = "Trang chủ"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Bài viết"
    url = "/posts/"
    weight = 2
